name: base
channels:
- defaults
- conda-forge
dependencies:
- python=3.9
# standard libraries
- anaconda::git
- conda-forge::gh
# terminal stuff
- conda-forge::tmux
- tmuxp
- zsh
- pip
- pip:
  - tmuxp
  - jupyter-book
  - wandb